"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { RecoveryData } from "../types";

interface AutoGeneratedContentProps {
  recoveryData: RecoveryData;
}

export default function AutoGeneratedContent({
  recoveryData,
}: AutoGeneratedContentProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Takaisinperinnän tiedot</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <h3 className="font-semibold mb-2">
            {recoveryData.consentAndHearing.title}
          </h3>
          <div className="bg-gray-50 p-4 rounded space-y-2">
            <p>
              <strong>Määrä:</strong>{" "}
              {recoveryData.consentAndHearing.amount.toFixed(2)} €
            </p>
            <p>
              <strong>Ajanjakso:</strong>{" "}
              {recoveryData.consentAndHearing.period}
            </p>
            <p>
              <strong>Syy:</strong> {recoveryData.consentAndHearing.reason}
            </p>
          </div>
        </div>

        <div>
          <h3 className="font-semibold mb-2">Takaisinperinnän määrä</h3>
          <div className="bg-gray-50 p-4 rounded space-y-2">
            <p>
              <strong>Yhteensä:</strong>{" "}
              {recoveryData.details.totalAmount.toFixed(2)} €
            </p>
            <div className="mt-2 space-y-1">
              {recoveryData.details.breakdown.map((item, idx) => (
                <div key={idx} className="text-sm">
                  {item.period}: {item.amount.toFixed(2)} €
                </div>
              ))}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

